### ISSUE TITLE
user name cannot be null or empty

### ISSUE THREAD

**Issue by naushadh** [nreco/presto-ado#2]
I tried to connect to a Presto cluster, but ran into an `ArgumentNullException`. When I set username using environment variable, the underlying PrestoClient library happily accepts that. I'd appreciate any guidance on how I can resolve this

```bash
$ docker run --rm -it -v $HOME/dev/MyApp:/app --workdir /app mcr.microsoft.com/dotnet/sdk bash
root@e14817128e98:/app# dotnet run
Unhandled exception. System.ArgumentNullException: The user name cannot be null or empty. (Parameter 'User')
   at BAMCIS.PrestoClient.PrestoClientSessionConfig.set_User(String value)
   at BAMCIS.PrestoClient.PrestoClientSessionConfig..ctor()
   at NReco.PrestoAdo.PrestoConnection.set_ConnectionString(String value)
   at NReco.PrestoAdo.PrestoConnection..ctor(String connectionString)
   at PrestoTest.CreateConnection() in /app/DataLinkSQL.cs:line 17
   at PrestoTest.Main() in /app/DataLinkSQL.cs:line 22
root@e14817128e98:/app# USER=bob dotnet run
Name or service not known (example.com:443)
```

```csharp
using System.Data;
using System.Data.Common;
using NReco.PrestoAdo;

// ADO.NET Examples: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ado-net-code-examples#adonet-data-provider-examples
// Retrieve data: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dbconnection-dbcommand-and-dbexception#retrieving-data-example
class MyApp
{
    static PrestoConnection CreateConnection()
    {
        return new PrestoConnection("Host=example.com;Port=443;User=bob;Password=secret;Catalog=main;Schema=public;UseSsl=True;");
    }

    static void Main()
    {
        using (PrestoConnection connection = CreateConnection())
        {
            string queryString =
            "SELECT ProductID, UnitPrice, ProductName from dbo.products "
                + "WHERE UnitPrice > @pricePoint "
                + "ORDER BY UnitPrice DESC";

            DbCommand command = connection.CreateCommand();
            command.CommandText = queryString;
            command.CommandType = CommandType.Text;

            DbParameter param1 = command.CreateParameter();
            param1.ParameterName = "@pricePoint";
            param1.Value = 5;
            command.Parameters.Add(param1);

            try
            {
                connection.Open();
                DbDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    Console.WriteLine("\t{0}\t{1}\t{2}",
                        reader[0], reader[1], reader[2]);
                }
                reader.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            Console.ReadLine();
        }
    }
}
```

```bash
$ dotnet list package --include-transitive
Project 'DataLinkSQL' has the following package references
   [net6.0]: 
   Top-level Package      Requested   Resolved
   > NReco.PrestoAdo      1.0.0       1.0.0   

   Transitive Package                                                                   Resolved
   > Microsoft.CSharp                                                                   4.7.0   
   > Microsoft.NETCore.Platforms                                                        1.1.1   
   > Microsoft.NETCore.Targets                                                          1.1.0   
   > Newtonsoft.Json                                                                    12.0.3  
   > PrestoClient                                                                       0.198.5 
   > runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl           4.3.2   
   > runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl          4.3.2   
   > runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl          4.3.2   
   > runtime.native.System                                                              4.3.0   
   > runtime.native.System.Net.Http                                                     4.3.0   
   > runtime.native.System.Security.Cryptography.Apple                                  4.3.0   
   > runtime.native.System.Security.Cryptography.OpenSsl                                4.3.2   
   > runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl      4.3.2   
   > runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl      4.3.2   
   > runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple            4.3.0   
   > runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl          4.3.2   
   > runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl             4.3.2   
   > runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl       4.3.2   
   > runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl       4.3.2   
   > runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl       4.3.2   
   > System.Collections                                                                 4.3.0   
   > System.Collections.Concurrent                                                      4.3.0   
   > System.ComponentModel                                                              4.3.0   
   > System.Diagnostics.Debug                                                           4.3.0   
   > System.Diagnostics.DiagnosticSource                                                4.3.0   
   > System.Diagnostics.Tracing                                                         4.3.0   
   > System.Globalization                                                               4.3.0   
   > System.Globalization.Calendars                                                     4.3.0   
   > System.Globalization.Extensions                                                    4.3.0   
   > System.IO                                                                          4.3.0   
   > System.IO.FileSystem                                                               4.3.0   
   > System.IO.FileSystem.Primitives                                                    4.3.0   
   > System.Linq                                                                        4.3.0   
   > System.Net.Http                                                                    4.3.4   
   > System.Net.Primitives                                                              4.3.0   
   > System.Reflection                                                                  4.3.0   
   > System.Reflection.Primitives                                                       4.3.0   
   > System.Resources.ResourceManager                                                   4.3.0   
   > System.Runtime                                                                     4.3.0   
   > System.Runtime.Extensions                                                          4.3.0   
   > System.Runtime.Handles                                                             4.3.0   
   > System.Runtime.InteropServices                                                     4.3.0   
   > System.Runtime.Numerics                                                            4.3.0   
   > System.Security.Cryptography.Algorithms                                            4.3.0   
   > System.Security.Cryptography.Cng                                                   4.3.0   
   > System.Security.Cryptography.Csp                                                   4.3.0   
   > System.Security.Cryptography.Encoding                                              4.3.0   
   > System.Security.Cryptography.OpenSsl                                               4.3.0   
   > System.Security.Cryptography.Primitives                                            4.3.0   
   > System.Security.Cryptography.X509Certificates                                      4.3.0   
   > System.Text.Encoding                                                               4.3.0   
   > System.Threading                                                                   4.3.0   
   > System.Threading.Tasks                                                             4.3.0
```

**Comment by VitaliyMF** [comment]
This is strange. In [PrestoConnection class](https://github.com/nreco/presto-ado/blob/master/src/NReco.PrestoAdo/PrestoConnection.cs) code I see:

```
        public sealed override string ConnectionString {
            get {
                return connectionString;
            }
            set {
                var builder = new PrestoConnectionStringBuilder(value);
                config = new PrestoClientSessionConfig() {
                    Host = builder.Host,
                    Port = builder.Port,
                    Catalog = builder.Catalog,
                    Schema = builder.Schema,
                    CheckInterval = builder.CheckInterval,
                    IgnoreSslErrors = builder.IgnoreSslErrors,
                    UseSsl = builder.UseSsl,
                    ClientRequestTimeout = builder.ClientRequestTimeout
                };
	            if (!String.IsNullOrEmpty(builder.User))
			 config.User = builder.User;
		   if (!String.IsNullOrEmpty(builder.Password))
                    config.Password = builder.Password;

                client = new PrestodbClient(config);
            }
        }
```

So if `User` is not set, it simply is not passed to PrestoClient's PrestoClientSessionConfig. Have you tried to exclude "User=" from the connection string at all?

**Comment by naushadh** [comment]
I get the same error when excluding `User` from the connection string.

**Comment by VitaliyMF** [comment]
This happens because of this code in the underlying PrestoClient library (see https://github.com/bamcis-io/PrestoClient/blob/0.256/PrestoClient/PrestoClientSessionConfig.cs ):

```
        public PrestoClientSessionConfig()
        {
            this.Host = _DEFAULT_HOST;
            this.Port = _DEFAULT_PORT;
            this.User = Environment.GetEnvironmentVariable("USERNAME") ?? Environment.GetEnvironmentVariable("USER");
```

because exception stacktrace shows that `set_User` is called from the constructor, not by NReco.PrestoAdo code:

```
Unhandled exception. System.ArgumentNullException: The user name cannot be null or empty. (Parameter 'User')
   at BAMCIS.PrestoClient.PrestoClientSessionConfig.set_User(String value)
   at BAMCIS.PrestoClient.PrestoClientSessionConfig..ctor()
```

This means that actually you don't have USER or USERNAME env variable, and this causes an exception. You can create an issue for PrestoClient to fix that (fix is trivial).

Also, the latest PrestoClient library doesn't support Trino headers yet (but codebase supports that in "vNext" branch), I've asked the maintainer [if he has plans to publish it](https://github.com/bamcis-io/PrestoClient/issues/14), if not I'll do a fork for NReco.PrestoAdo provider and then can fix this issue too.

**Comment by VitaliyMF** [comment]
@naushadh I've published NReco.PrestoAdo 1.1 that depends on PrestoClient 0.351.0-beta that is now available. This PrestoClient can switch between "X-Presto-" and "X-Trino-" headers, and now NReco.PrestoAdo also can use Trino headers -- to enable Trino prefix it is enough to include "TrinoHeaders=1" into a connection string.

However, PrestoClient still expects either "USERNAME" or "USER" environment variable and if they are not set (or empty) exception occurs. Only workaround for now is setting 'fake' "USERNAME" env variable.

**Comment by naushadh** [comment]
Thank you; I'd added `0.351.0-beta` to the project and was able to use PrestoAdo 1.0 as is.
Agreed, will follow up with upstream project re the username config flow.
